//
//  InvestmentsPresenter.swift
//  TesteiOS
//
//  Created by Gustavo Chaves on 23/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentsPresentationLogic
{
  func presentSomething(response: Investments.Something.Response)
}

class InvestmentsPresenter: InvestmentsPresentationLogic
{
  weak var viewController: InvestmentsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Investments.Something.Response)
  {
    let viewModel = Investments.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
