//
//  InvestmentsInteractor.swift
//  TesteiOS
//
//  Created by Gustavo Chaves on 23/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestmentsBusinessLogic
{
  func doSomething(request: Investments.Something.Request)
}

protocol InvestmentsDataStore
{
  //var name: String { get set }
}

class InvestmentsInteractor: InvestmentsBusinessLogic, InvestmentsDataStore
{
  var presenter: InvestmentsPresentationLogic?
  var worker: InvestmentsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Investments.Something.Request)
  {
    worker = InvestmentsWorker()
    worker?.doSomeWork()
    
    let response = Investments.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
