//
//  LoginInteractor.swift
//  Test
//
//  Created by Gustavo Chaves on 29/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func doSomething(request: Login.Something.Request)
  func getLoginStoredData()
}

protocol LoginDataStore
{
  //var name: String { get set }
    var response: Login.Something.Response? {get}
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  var response: Login.Something.Response?
  // MARK: Do something
  
  func doSomething(request: Login.Something.Request)
  {
    let user = request.user
    let password = request.password
    if !password.isValid(.password){
        self.presenter?.presentError(error: Login.Something.Error(code: nil, message: "Senha muito simples!"))
        return
    }
    if !user.isValid(.email) && !user.isValid(.cpf){
        self.presenter?.presentError(error: Login.Something.Error(code: nil, message: "Utilize CPF ou Email para Login"))
        return
    }
    worker = LoginWorker()
    worker?.doLogin(user: user, password: password){ loginResponse in
        if let error = loginResponse.error {
            self.presenter?.presentError(error: Login.Something.Error(code: error.code, message: error.message ?? ""))
            return
        }
        guard let userAccount = loginResponse.userAccount else {return}
        self.response = Login.Something.Response(id: userAccount.userId!, name: userAccount.name!, agency: userAccount.agency!, account: userAccount.bankAccount!, balance: userAccount.balance!)
        self.presenter?.presentSomething(response: self.response!)
        KeychainHelper.save(key: "user", data: user)
        KeychainHelper.save(key: "password", data: password)
        }

    }
    
    func getLoginStoredData(){
        let user = KeychainHelper.load(key: "user")
        let password = KeychainHelper.load(key: "password")
        
        let loginData = Login.Something.LoginData(user: user?.toString() ?? "", password: password?.toString() ?? "")
        presenter?.presentLoginData(loginData: loginData)
        
    }
}

