//
//  LoginInteractor.swift
//  Test
//
//  Created by Gustavo Chaves on 29/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func doSomething(request: Login.Something.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
    var response: Login.Something.Response? {get}
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  var response: Login.Something.Response?
  // MARK: Do something
  
  func doSomething(request: Login.Something.Request)
  {
    let user = request.user
    let password = request.password
    worker = LoginWorker()
    worker?.doLogin(user: user, password: password){ loginResponse in
        let userAccount = loginResponse.userAccount
        self.response = Login.Something.Response(id: userAccount.userId!, name: userAccount.name!, agency: userAccount.agency!, account: userAccount.bankAccount!, balance: userAccount.balance!)
        self.presenter?.presentSomething(response: self.response!)
    }
  }
}
