//
//  StatementsPresenter.swift
//  Test
//
//  Created by Gustavo Chaves on 29/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsPresentationLogic
{
  func presentUser(response: Statements.UserData.Response)
}

class StatementsPresenter: StatementsPresentationLogic
{
  weak var viewController: StatementsDisplayLogic?
  
  // MARK: Do something
  
  func presentUser(response: Statements.UserData.Response)
  {
    
    let balance = response.userBalance.formatToCurrency()//currencyFormatter.string(from: response.userBalance as NSNumber) ?? "\(response.userBalance)"
    
    let agency = response.userAgency.applyPatternOnNumbers(pattern: "##.######-#", replacmentCharacter: "#")
    let viewModel = Statements.UserData.ViewModel(userName: response.userName, userAccount: response.userAccount, userAgency: agency, userBalance: balance)
    viewController?.displayUser(viewModel: viewModel)
  }
}
