//
//  LoginWorker.swift
//  TesteiOS
//
//  Created by Gustavo Chaves on 23/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func doSomeWork(success: @escaping(([Cell]) -> ()))
  {
    Service.shared.fetchLoginForm{(formResult, err) in
               if let err = err {
                   print("Failed to fetch form:", err)
                   return
               }
        success(formResult)
           }
  } 
}
