//
//  LoginModels.swift
//  TesteiOS
//
//  Created by Gustavo Chaves on 23/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var formFormat: [Cell]
    }
    struct ViewModel
    {
        var view: UIView
    }
  }
    

}
