//
//  LoginPresenter.swift
//  TesteiOS
//
//  Created by Gustavo Chaves on 23/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentSomething(response: Login.Something.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login.Something.Response)
  {
    response.formFormat.forEach { (cell) in
        cell.viewFrom { (view) in
            let viewModel = Login.Something.ViewModel(view: view)
            self.viewController?.displaySomething(viewModel: viewModel)
        }
        //print(view.subviews[0])
        
    }
    

  }
    
    

}
