//
//  LoginInteractor.swift
//  TesteiOS
//
//  Created by Gustavo Chaves on 23/04/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func doSomething(request: Login.Something.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
    var formFormat: [Cell] { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
    var formFormat: [Cell] = []
    
  
  // MARK: Do something
  
  func doSomething(request: Login.Something.Request)
  {
    worker = LoginWorker()
    (worker?.doSomeWork(success: { formFormat in
        let response = Login.Something.Response(formFormat: formFormat)
        self.presenter?.presentSomething(response: response)
    }))
    
  }
}
